server:
  port: 9999
#mybtis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.maple.smaple.dao.mapper.bo

spring:
  datasource:
    username: root
    password: mysql
    url: jdbc:mysql://localhost:3306/smaple?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
  redis:
    host: 47.101.218.112
    port: 6379
    password: 123456
#    关闭thymeleaf缓存
#    thymeleaf
#      cache:false
